### ISSUE TITLE
Compatibility with Akeneo CE 4.0

### ISSUE THREAD

**Issue by dalarcia** [FriendsOfAkeneo/CustomEntityBundle#212]
Hi group.

Is this bundle going to be compatible with Akeneo CE 4.0? And if so, could you tell us if there is any realease date?

Thanks in advance.

Best regards. 
David.

**Comment by nicolasfl** [comment]
Hi David, 
I asked the same question to the team and they told me that for now, the custom entity bundle is not in their roadmap because the Reference Entities feature is now available since 3.0. 
Of course, if someone decides to do the upgrade in a PR, they would be very happy to review it. 
Nicolas

**Comment by dalarcia** [comment]
Hi Nicolas.

Thank you very much for the answare. So, Does this means that it is not possible to use reference data types (single or multiple) in Akeneo 4.0? 
I have searched on how to use this data types in the Akeneo docs for the 4.0 version and I can not get any information.

Best regards.

**Comment by jmleroux** [comment]
Hi,
This is not documented anymore because we are focusing on Reference Entities for the PIM, but the reference data is still present and it should be possible to use it with this bundle once/if is is updated.
We don't have time to work on it right now and that's why we opened it to the community to respect our open source vision.

Best regards.

**Comment by gplanchat** [comment]
Hello,

As this bundle has been migrated to the FriendsOfAkeneo organization, it is now under the leadership of the community.

Feel free to contribute or join the [#friends-of-akeneo](https://akeneopim-ug.slack.com/archives/CUFM98C8P) Slack channel to discuss about it
